# Generated by Django 5.2.8 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Productcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('Design', models.CharField(max_length=20)),
                ('Colour', models.CharField(max_length=10)),
                ('Stock', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
